name: findflow_mobile
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus:
  permission_handler:
  flutter_foreground_task: ^8.14.0
  flutter_local_notifications: 18.0.1
  freezed: ^2.5.7
  build_runner: ^2.4.13
  dio: ^5.7.0
  http: ^1.2.2
  freezed_annotation: ^2.4.4
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/find_flow_logo.png
